version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
# Uncomment / enable when you add a frontend package.json
#  - package-ecosystem: "npm"
#    directory: "/frontend"
#    schedule:
#      interval: "weekly"
